auzonet/auzonet/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from rest_framework import routers

from auzonetweb import views

router = routers.DefaultRouter()
router.register(r'categories', views.CategoryViewSet)
router.register(r'communities', views.CommunityViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^my-profile/$', views.user_profile, name='my-profile'),
    url(r'^delete-post/(?P<postid>\d+)/(?P<posttype>["R","O"]+)/$', views.delete_post, name='delete-post'),
    url(r'^recover-post/(?P<postid>\d+)/(?P<posttype>["R","O"]+)/$', views.recover_post, name='recover-post'),
    url(r'^delete-message/(?P<messageid>\d+)/$', views.delete_message, name='delete-message'),
    url(r'^confirmation-success/(?P<orderid>\d+)/$', views.confirmation_success, name='confirmation-success'),
    url(r'^finalize-order/(?P<orderid>\d+)/(?P<feedback>["0","1"]+)/$', views.finalize_order, name='finalize-order'),
    url(r'^wizard/$', views.wizard, name='wizard'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^register-public-profile/$', views.register_public_profile, name='register-public-profile'),
    url(r'^bootcamp/$', views.bootcamp, name='bootcamp'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^edit-offer/(?P<offerid>\d+)/$', views.edit_offer, name='edit-offer'),
    url(r'^detail-offer/(?P<offerid>\d+)/$', views.detail_offer, name='detail-offer'),
    url(r'^accept-offer/(?P<orderid>\d+)/$', views.accept_offer, name='accept-offer'),
    url(r'^hire-offer/(?P<offerid>\d+)/$', views.hire_offer, name='hire-offer'),
    url(r'^edit-request/(?P<requestid>\d+)/$', views.edit_request, name='edit-request'),
    url(r'^detail-request/(?P<requestid>\d+)/$', views.detail_request, name='detail-request'),
    url(r'^accept-request/(?P<orderid>\d+)/$', views.accept_request, name='accept-request'),
    url(r'^hire-request/(?P<requestid>\d+)/$', views.hire_request, name='hire-request'),
    url(r'^community/(?P<comid>\d+)/$', views.index, name='indexcommunity'),
    url(r'^confirmationsent/(?P<info>\d+)/$', views.index, name='index-message'),
    url(r'^protectedcommunity/(?P<comid>\d+)/$', views.protected_community, name='protectedcommunity'),
    url(r'^new-offer/$', views.edit_offer, name='new-offer'),
    url(r'^new-request/$', views.edit_request, name='new-request'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^auzonetweb/media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^admin/', admin.site.urls),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^', include(router.urls)),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
]

auzonet/auzonetweb/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy
from rest_framework import serializers

GENDERS = (
    ('M', 'Male'),
    ('F', 'Female')
)
ACCESS_TYPE = (
    ('PU', 'Public'),
    ('PR', 'Private'),
)
ORDER_TYPES = (
    ('O', 'Offer'),
    ('R', 'Request'),
)
STATUS = (
    ('A', 'Active'),
    ('P', 'Pending'),
    ('F', 'Finished'),
)

SCOPE = (
    ('COM', 'Community'),
    ('CIT', 'City'),
    ('PRO', 'Province'),
)
MESSAGE_TYPES = (
    ('I', ugettext_lazy(u'Info')),
    ('W', ugettext_lazy(u'Warning')),
)


class Community(models.Model):
    class Meta:
        verbose_name_plural = "Communities"

    access_type = models.CharField(ugettext_lazy(u'Tipo de acceso'), max_length=2, choices=ACCESS_TYPE, default='PU',
                                   help_text=ugettext_lazy(u"You can protect with password the community access."))
    neighborhood_code = models.IntegerField()
    neighborhood_name = models.CharField(max_length=250)
    street_code = models.IntegerField()
    street_name = models.CharField(max_length=250)
    door_code = models.IntegerField()
    coordinatesX = models.DecimalField(decimal_places=2, max_digits=10, default=0, blank=True, null=True)
    coordinatesY = models.DecimalField(decimal_places=2, max_digits=10, default=0, blank=True, null=True)
    password = models.CharField(ugettext_lazy(u'Password'), blank=True, max_length=250)
    welcome_message = models.TextField(ugettext_lazy(u'Mensaje de bienvenida'), help_text=ugettext_lazy(u"This text will be sent to new users in your community."), )

    def __unicode__(self):
        return self.neighborhood_name + ', ' + self.street_name + ', ' + str(self.door_code)


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"

    title = models.CharField(max_length=250)
    description = models.TextField()

    def __unicode__(self):
        return self.title


class Request(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=ugettext_lazy(u'Category'))
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="requested_by")
    title = models.CharField(ugettext_lazy(u'Title'), max_length=250)
    detail = models.TextField(ugettext_lazy(u'Detail'))
    date_published = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField(ugettext_lazy(u'Due date'), blank=True, null=True)
    scope = models.CharField(max_length=3, choices=SCOPE, default='COM')
    status = models.CharField(max_length=1, choices=STATUS, default='A')
    reward = models.DecimalField(ugettext(u'Reward'), blank=True, null=True, decimal_places=2, max_digits=10, default=0,
                                 help_text=ugettext_lazy(u"EUR. Leave it blank for no reward."))
    image = models.ImageField(ugettext_lazy(u'Image'), blank=True, upload_to='uploads/requests/%Y/%m/%d/')

    def __unicode__(self):
        return self.title + " created on " + str(self.date_published)


class Offer(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=ugettext_lazy(u'Category'))
    community = models.ForeignKey(Community, on_delete=models.CASCADE, verbose_name=ugettext_lazy(u'Community'))
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="offered_by")
    title = models.CharField(ugettext_lazy(u'Title'), max_length=250)
    detail = models.TextField(ugettext_lazy(u'Detail'))
    date_published = models.DateTimeField(auto_now_add=True)
    scope = models.CharField(max_length=3, choices=SCOPE, default='COM')
    status = models.CharField(max_length=1, choices=STATUS, default='A')
    price = models.DecimalField(ugettext_lazy(u'Price'), blank=True, null=True, decimal_places=2, max_digits=10, default=0,
                                help_text=ugettext_lazy(u"EUR. Leave it blank for no price."))
    image = models.ImageField(ugettext_lazy(u'Image'), blank=True, upload_to='uploads/offers/%Y/%m/%d/')

    def __unicode__(self):
        return self.title + " created on " + str(self.date_published)


class Order(models.Model):
    order_type = models.CharField(max_length=1, choices=ORDER_TYPES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="server")
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name="client")
    offer = models.ForeignKey(Offer, blank=True, null=True, on_delete=models.CASCADE)
    auzonetrequest = models.ForeignKey(Request, blank=True, null=True, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    owner_voted = models.BooleanField(blank=True, default=False)
    client_voted = models.BooleanField(blank=True, default=False)
    status = models.CharField(max_length=1, choices=STATUS, default='A')

    def __unicode__(self):
        return "Client: " + self.client.username + " Owner: " + self.owner.username + " Type: " + self.order_type + " Created on: " + str(
            self.date_created)


# fist_name, last_name, email, password belongs to superclass User
class PublicUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    communities = models.ManyToManyField(Community)
    birthdate = models.DateField(null=True)
    gender = models.CharField(max_length=1, choices=GENDERS)
    karma = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='uploads/avatars/%Y/%m/%d/')

    def __unicode__(self):
        return self.user.username

    def get_source_filename(self):
        return str(self.avatar.file)

    def save(self, size=(500, 300)):
        """
        Save Photo after ensuring it is not blank.  Resize as needed.
        """

        if not self.id and not self.avatar:
            return

        super(PublicUser, self).save()

        # filename = self.get_source_filename()
        # image = Image.open(filename)

        # image.thumbnail(size, Image.ANTIALIAS)
        # image.save(filename)


class CommunityMessage(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    message_type = models.CharField(ugettext_lazy(u'Message type'), max_length=1, choices=MESSAGE_TYPES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posted_by")
    date_published = models.DateTimeField(auto_now_add=True)
    message_text = models.TextField(ugettext_lazy(u'Texto'))

    def __unicode__(self):
        return self.message_type + " created on " + str(self.date_published)


class CategoriesSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Category
        fields = ('title', 'description')


class CommunitiesSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Community
        fields = (
            'access_type',
            'neighborhood_code',
            'neighborhood_name',
            'street_code',
            'street_name',
            'door_code',
            'coordinatesX',
            'coordinatesY',
            'password',
            'welcome_message'
        )

auzonet/auzonetweb/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy

from .models import Community, Request, Offer, CommunityMessage

GENDERS = (
    ('M', ugettext_lazy(u"Male")),
    ('F', ugettext_lazy(u"Female"))
)

ACCESS_TYPES = (
    ('PU', ugettext_lazy(u"Public")),
    ('PR', ugettext_lazy(u"Private")),
)

SCOPE = (
    ('COM', ugettext_lazy(u"Community")),
    ('CIT', ugettext_lazy(u"City")),
    ('PRO', ugettext_lazy(u"Province")),
    ('COU', ugettext_lazy(u"Country")),
)

STATUS = (
    ('A', ugettext_lazy(u"Active")),
    ('F', ugettext_lazy(u"Finished")),
)


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label=ugettext_lazy(u"Username"), max_length=100)
    password = forms.CharField(required=True, label=ugettext_lazy(u"Password"), max_length=100,
                               widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    class Meta:
        localized_fields = '__all__'

    username = forms.CharField(required=True, label=ugettext_lazy(u"Username"), max_length=100,
                               help_text=ugettext_lazy(u"* Required"))
    first_name = forms.CharField(required=True, label=ugettext_lazy(u"Name"), max_length=100,
                                 help_text=ugettext_lazy(u"* Required"))
    last_name = forms.CharField(required=True, label=ugettext_lazy(u"Surname"), max_length=100,
                                help_text=ugettext_lazy(u"* Required"))
    email = forms.EmailField(required=True, label=ugettext_lazy(u"Email"), max_length=100, widget=forms.EmailInput,
                             help_text=ugettext_lazy(u"* Required"))
    password = forms.CharField(required=True, label=ugettext_lazy(u"Password"), max_length=100,
                               widget=forms.PasswordInput,
                               help_text=ugettext_lazy(u"* Required"))
    birthdate = forms.DateField(required=True, label=ugettext_lazy(u"Birthday"), help_text=ugettext_lazy(u"* Required"))
    gender = forms.ChoiceField(required=True, label=ugettext_lazy(u"Gender"), choices=GENDERS,
                               help_text=ugettext_lazy(u"* Required"))
    avatar = forms.ImageField(required=True, label=ugettext_lazy(u"Avatar"), max_length=100,
                              help_text=ugettext_lazy(u"* Required. Will be your public image in the community."))


class RegisterPublicForm(forms.Form):
    class Meta:
        localized_fields = '__all__'

    birthdate = forms.DateField(required=True, label=ugettext_lazy(u"Birthday"), help_text=ugettext_lazy(u"* Required"))
    gender = forms.ChoiceField(required=True, label=ugettext_lazy(u"Gender"), choices=GENDERS,
                               help_text=ugettext_lazy(u"* Required"))
    avatar = forms.ImageField(required=True, label=ugettext_lazy(u"Avatar"), max_length=100,
                              help_text=ugettext_lazy(u"* Required. Will be your public image in the community."))


class JoinCommunityForm(forms.Form):
    community = forms.ModelChoiceField(queryset=Community.objects.all())


class ProtectedCommunityForm(forms.Form):
    password = forms.CharField(required=True, label=ugettext_lazy(u"Password"), max_length=100,
                               widget=forms.PasswordInput)


class NewCommunityMsgModelForm(ModelForm):
    class Meta:
        model = CommunityMessage
        fields = ['message_type', 'message_text']
        localized_fields = '__all__'


class NewCommunityForm(forms.Form):
    access_type = forms.ChoiceField(label=ugettext_lazy(u"Tipo de acceso"), choices=ACCESS_TYPES)
    neighborhood_code = forms.IntegerField(widget=forms.HiddenInput)
    neighborhood_name = forms.CharField(widget=forms.HiddenInput)
    street_code = forms.IntegerField(widget=forms.HiddenInput)
    street_name = forms.CharField(widget=forms.HiddenInput)
    door_code = forms.IntegerField(widget=forms.HiddenInput)
    coordinatesX = forms.DecimalField(widget=forms.HiddenInput)
    coordinatesY = forms.DecimalField(widget=forms.HiddenInput)
    password = forms.CharField(label=ugettext_lazy(u"Password"), widget=forms.PasswordInput, required=False)
    welcome_message = forms.CharField(label=ugettext_lazy(u"Mensaje de bienvenida"), widget=forms.Textarea, required=False)

    class Meta:
        localized_fields = '__all__'


class NewOfferModelForm(ModelForm):
    class Meta:
        model = Offer
        localized_fields = '__all__'
        fields = ['category', 'title', 'detail', 'price', 'image']


class NewRequestModelForm(ModelForm):
    class Meta:
        model = Request
        localized_fields = '__all__'
        fields = ['category', 'title', 'detail', 'due_date', 'reward', 'image']

auzonet/auzonetweb/templates/auzonetweb/Request/detail-request.html
{% extends "auzonetweb/base.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}
{% block scripts %}
    <script>
    </script>
{% endblock %}

{% block title %}AuzoNet - {{ auzonetrequest.title }}{% endblock %}
{% block content %}
    {% if is_client == 1 %}
        <!-- Modal finalize order by client-->
        <div class="modal fade" id="confirmEndClientModal" tabindex="-1" role="dialog"
             aria-labelledby="finalizeClientModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="finalizeClientModal">Terminar acuerdo</h4>
                    </div>
                    <div class="modal-body">
                        ¿Estás satisfecho con el trato de {{ auzonetrequest.owner.username }}?
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-lg btn-success"
                           href="{% url 'finalize-order' orderid=client_order.id feedback='1' %}" role="button"><span
                                class="glyphicon glyphicon-thumbs-up"></span> Si</a>
                        <a class="btn btn-lg btn-danger"
                           href="{% url 'finalize-order' orderid=client_order.id feedback='0' %}" role="button"><span
                                class="glyphicon glyphicon-thumbs-down"></span> No</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <!-- Modal delete-->
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog"
         aria-labelledby="confirmDeleteModalTitle">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="confirmDeleteModalTitle">Cancelar petición</h4>
                </div>
                <div class="modal-body">
                    ¿Seguro que quieres cancelar tu petición? <br>
                    Recuerda que siempre puedes ponerla de nuevo a la vista desde tu panel de usuario.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No hacer cambios</button>
                    <a class="btn btn-danger" href="{% url 'delete-post' postid=auzonetrequest.id posttype='R' %}"
                       role="button">Cancelar petición</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal hiring-->
    <div class="modal fade" id="confirmHireModal" tabindex="-1" role="dialog" aria-labelledby="confirmHireModalTitle">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="confirmHireModalTitle">¿Seguro que atender esta petición?</h4>
                </div>
                <div class="modal-body">
                    Se enviará un email a <b>{{ auzonetrequest.owner.username }}</b> para informar de que quieres
                    atender su petición. Recibirás un aviso si <b>{{ auzonetrequest.owner.username }}</b> lo acepta.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" href="{% url 'hire-request' requestid=auzonetrequest.id %}"
                       role="button">Atender</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="row">
            <div class="col-md-3">
                <p class="lead text-center">
                    {% if  auzonetrequest.owner.publicuser.avatar %}
                        {% static auzonetrequest.owner.publicuser.avatar.url as avatar %}
                        <img src="{{ avatar }}" height="150" width=auto class="thumbnail center-block"
                             alt="owner_avatar"/>
                    {% endif %}
                    {{ auzonetrequest.owner.first_name }} {{ auzonetrequest.owner.last_name }}
                    ({{ auzonetrequest.owner }})
                    <br>
                    Karma: {{ auzonetrequest.owner.publicuser.karma }}
                </p>
                {% if auzonetrequest.owner.id == request.user.id %}
                    {% if orders.count > 0 %}
                        <div class="panel panel-default">
                            <div class="panel-heading">Acuerdos</div>
                            <div class="panel-body">
                                {% for o in orders %}
                                    <!-- Modal finalize order by owner-->
                                    <div class="modal fade" id="confirmEndOwnerModal" tabindex="-1" role="dialog"
                                         aria-labelledby="finalizeOwnerModal">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close"><span aria-hidden="true">&times;</span>
                                                    </button>
                                                    <h4 class="modal-title" id="finalizeOwnerModal">Terminar
                                                        acuerdo</h4>
                                                </div>
                                                <div class="modal-body">
                                                    ¿Estás satisfecho con el trato de {{ o.client.username }}?
                                                </div>
                                                <div class="modal-footer">
                                                    <a class="btn btn-lg btn-success"
                                                       href="{% url 'finalize-order' orderid=o.id feedback='1' %}"
                                                       role="button"><span class="glyphicon glyphicon-thumbs-up"></span>
                                                        Si</a>
                                                    <a class="btn btn-lg btn-danger"
                                                       href="{% url 'finalize-order' orderid=o.id feedback='0' %}"
                                                       role="button"><span
                                                            class="glyphicon glyphicon-thumbs-down"></span> No</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="media">
                                        <div class="media-left">
                                            <a href="#">
                                                <img class="media-object"
                                                     src="{% static o.client.publicuser.avatar.url %}" height="64"
                                                     width="64" alt="...">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">{{ o.client.username }}</h4>
                                            {{ o.date_created }} <br>
                                            {% if o.owner_voted %}
                                                <button class="btn btn-default btn-xs btn-block" disabled>Esperando
                                                    valoración de {{ o.client.username }}</button>
                                            {% else %}
                                                <button data-target="#confirmEndOwnerModal" data-toggle="modal"
                                                        class="btn btn-default btn-xs btn-block"><span
                                                        class="glyphicon glyphicon-ok"></span> Terminar acuerdo
                                                </button>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                    {% endif %}
                    <a class="btn btn-warning btn-block" href="{% url 'edit-request' auzonetrequest.id %}"
                       role="button">Editar</a>
                    <button id="btn-finish" class="btn btn-danger btn-block" data-toggle="modal"
                            data-target="#confirmDeleteModal">Cancelar
                    </button>
                {% else %}
                    {% if is_client == 1 %}
                        {% if client_order.client_voted %}
                            <button class="btn btn-default btn-block" disabled>Esperando valoración
                                de {{ client_order.owner.username }}</button>
                        {% else %}
                            <button id="btn-cancel" class="btn btn-danger btn-block" data-toggle="modal"
                                    data-target="#confirmEndClientModal">Terminar acuerdo
                            </button>
                        {% endif %}
                    {% else %}
                        <button id="btn-hire" class="btn btn-success btn-block" data-toggle="modal"
                                data-target="#confirmHireModal">Atender petición
                        </button>
                    {% endif %}
                {% endif %}

                <a class="btn btn-default btn-block" href="{% url 'index' %}" role="button">Volver</a>
            </div>

            <div class="col-md-9">
                <div class="thumbnail">
                    <div class="caption-full">
                        <h4 class="pull-right">
                            {% if auzonetrequest.reward == 0 %}
                                Gratis
                            {% else %}
                                Precio: {{ auzonetrequest.reward }} €
                            {% endif %}
                        </h4>
                        {% if auzonetrequest.due_date == None  %}
                            <h4><a href="#">{{ auzonetrequest.title }}</a></h4>
                        {% else %}
                            <h4><a href="#">{{ auzonetrequest.title }} antes del {{ auzonetrequest.due_date }}</a></h4>
                        {% endif %}
                        <p>{{ auzonetrequest.detail }}</p>
                    </div>
                    {% if auzonetrequest.image %}
                        {% static auzonetrequest.image.url as photo %}
                        <img src="{{ photo }}" height="800" width="300" class="img-resposive" alt="request_photo"/>
                    {% else %}
                        <img class="img-responsive" src="http://placehold.it/800x300" alt="" height="300" width="800">
                    {% endif %}
                </div>
                {% if auzonetrequest.owner.id != request.user.id %}
                    <div class="well">
                        <div class="text-right">
                            <button id="btn-hire" class="btn btn-success " data-toggle="modal"
                                    data-target="#confirmHireModal">Atender petición
                            </button>
                        </div>
                    </div>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock %}

auzonet/auzonetweb/templates/auzonetweb/Request/edit-request.html
{% extends "auzonetweb/base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load static from staticfiles %}
{% block scripts %}
<script>
$(document).ready(function(){
    $("#id_due_date").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: "yy-mm-dd"
    });
    $("#id_reward").numeric();
});
</script>
{% endblock %}

{% block title %}{% trans "AuzoNet - Nueva petición" %}{% endblock %}
{% block content%}
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <h1>Necesito</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% if errorMessage != None%}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>Error:</strong> {{ errorMessage }}
                </div>
            {% endif %}
            {% csrf_token %}
            {% bootstrap_form requestForm%}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% trans "Publicar" %}
            </button>
            <a class="btn btn-danger" href="{% url 'index' %}">{% trans "Cancelar" %}</a>
            {% endbuttons %}
        </form>
    </div>
    <div class="col-lg-3"></div>
</div> <!-- end my topics-->
{% endblock %}

auzonet/auzonetweb/templates/auzonetweb/Request/request.html
{% extends "auzonetweb/base.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}
{% block scripts %}
<script>
$(document).ready(function(){
    $("#id_due_date").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: "yy-mm-dd"
    });

});
</script>
{% endblock %}

{% block title %}AuzoNet - Nueva petición{% endblock %}
{% block content%}
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <h1>Necesito</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% if errorMessage != None%}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>Error:</strong> {{ errorMessage }}
                </div>
            {% endif %}
            {% csrf_token %}
            {% bootstrap_form requestForm%}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Publicar
            </button>
            <a class="btn btn-danger" href="{% url 'index' %}">Cancelar</a>
            {% endbuttons %}
        </form>
    </div>
    <div class="col-lg-3"></div>
</div> <!-- end my topics-->
{% endblock %}