auzonet/auzonet/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from rest_framework import routers

from auzonetweb import views

router = routers.DefaultRouter()
router.register(r'categories', views.CategoryViewSet)
router.register(r'communities', views.CommunityViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^my-profile/$', views.user_profile, name='my-profile'),
    url(r'^delete-post/(?P<postid>\d+)/(?P<posttype>["R","O"]+)/$', views.delete_post, name='delete-post'),
    url(r'^recover-post/(?P<postid>\d+)/(?P<posttype>["R","O"]+)/$', views.recover_post, name='recover-post'),
    url(r'^delete-message/(?P<messageid>\d+)/$', views.delete_message, name='delete-message'),
    url(r'^confirmation-success/(?P<orderid>\d+)/$', views.confirmation_success, name='confirmation-success'),
    url(r'^finalize-order/(?P<orderid>\d+)/(?P<feedback>["0","1"]+)/$', views.finalize_order, name='finalize-order'),
    url(r'^wizard/$', views.wizard, name='wizard'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^register-public-profile/$', views.register_public_profile, name='register-public-profile'),
    url(r'^bootcamp/$', views.bootcamp, name='bootcamp'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^edit-offer/(?P<offerid>\d+)/$', views.edit_offer, name='edit-offer'),
    url(r'^detail-offer/(?P<offerid>\d+)/$', views.detail_offer, name='detail-offer'),
    url(r'^accept-offer/(?P<orderid>\d+)/$', views.accept_offer, name='accept-offer'),
    url(r'^hire-offer/(?P<offerid>\d+)/$', views.hire_offer, name='hire-offer'),
    url(r'^edit-request/(?P<requestid>\d+)/$', views.edit_request, name='edit-request'),
    url(r'^detail-request/(?P<requestid>\d+)/$', views.detail_request, name='detail-request'),
    url(r'^accept-request/(?P<orderid>\d+)/$', views.accept_request, name='accept-request'),
    url(r'^hire-request/(?P<requestid>\d+)/$', views.hire_request, name='hire-request'),
    url(r'^community/(?P<comid>\d+)/$', views.index, name='indexcommunity'),
    url(r'^confirmationsent/(?P<info>\d+)/$', views.index, name='index-message'),
    url(r'^protectedcommunity/(?P<comid>\d+)/$', views.protected_community, name='protectedcommunity'),
    url(r'^new-offer/$', views.edit_offer, name='new-offer'),
    url(r'^new-request/$', views.edit_request, name='new-request'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^auzonetweb/media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^admin/', admin.site.urls),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^', include(router.urls)),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
]

auzonet/auzonetweb/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy
from rest_framework import serializers

GENDERS = (
    ('M', 'Male'),
    ('F', 'Female')
)
ACCESS_TYPE = (
    ('PU', 'Public'),
    ('PR', 'Private'),
)
ORDER_TYPES = (
    ('O', 'Offer'),
    ('R', 'Request'),
)
STATUS = (
    ('A', 'Active'),
    ('P', 'Pending'),
    ('F', 'Finished'),
)

SCOPE = (
    ('COM', 'Community'),
    ('CIT', 'City'),
    ('PRO', 'Province'),
)
MESSAGE_TYPES = (
    ('I', ugettext_lazy(u'Info')),
    ('W', ugettext_lazy(u'Warning')),
)


class Community(models.Model):
    class Meta:
        verbose_name_plural = "Communities"

    access_type = models.CharField(ugettext_lazy(u'Tipo de acceso'), max_length=2, choices=ACCESS_TYPE, default='PU',
                                   help_text=ugettext_lazy(u"You can protect with password the community access."))
    neighborhood_code = models.IntegerField()
    neighborhood_name = models.CharField(max_length=250)
    street_code = models.IntegerField()
    street_name = models.CharField(max_length=250)
    door_code = models.IntegerField()
    coordinatesX = models.DecimalField(decimal_places=2, max_digits=10, default=0, blank=True, null=True)
    coordinatesY = models.DecimalField(decimal_places=2, max_digits=10, default=0, blank=True, null=True)
    password = models.CharField(ugettext_lazy(u'Password'), blank=True, max_length=250)
    welcome_message = models.TextField(ugettext_lazy(u'Mensaje de bienvenida'), help_text=ugettext_lazy(u"This text will be sent to new users in your community."), )

    def __unicode__(self):
        return self.neighborhood_name + ', ' + self.street_name + ', ' + str(self.door_code)


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"

    title = models.CharField(max_length=250)
    description = models.TextField()

    def __unicode__(self):
        return self.title


class Request(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=ugettext_lazy(u'Category'))
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="requested_by")
    title = models.CharField(ugettext_lazy(u'Title'), max_length=250)
    detail = models.TextField(ugettext_lazy(u'Detail'))
    date_published = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField(ugettext_lazy(u'Due date'), blank=True, null=True)
    scope = models.CharField(max_length=3, choices=SCOPE, default='COM')
    status = models.CharField(max_length=1, choices=STATUS, default='A')
    reward = models.DecimalField(ugettext(u'Reward'), blank=True, null=True, decimal_places=2, max_digits=10, default=0,
                                 help_text=ugettext_lazy(u"EUR. Leave it blank for no reward."))
    image = models.ImageField(ugettext_lazy(u'Image'), blank=True, upload_to='uploads/requests/%Y/%m/%d/')

    def __unicode__(self):
        return self.title + " created on " + str(self.date_published)


class Offer(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=ugettext_lazy(u'Category'))
    community = models.ForeignKey(Community, on_delete=models.CASCADE, verbose_name=ugettext_lazy(u'Community'))
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="offered_by")
    title = models.CharField(ugettext_lazy(u'Title'), max_length=250)
    detail = models.TextField(ugettext_lazy(u'Detail'))
    date_published = models.DateTimeField(auto_now_add=True)
    scope = models.CharField(max_length=3, choices=SCOPE, default='COM')
    status = models.CharField(max_length=1, choices=STATUS, default='A')
    price = models.DecimalField(ugettext_lazy(u'Price'), blank=True, null=True, decimal_places=2, max_digits=10, default=0,
                                help_text=ugettext_lazy(u"EUR. Leave it blank for no price."))
    image = models.ImageField(ugettext_lazy(u'Image'), blank=True, upload_to='uploads/offers/%Y/%m/%d/')

    def __unicode__(self):
        return self.title + " created on " + str(self.date_published)


class Order(models.Model):
    order_type = models.CharField(max_length=1, choices=ORDER_TYPES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="server")
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name="client")
    offer = models.ForeignKey(Offer, blank=True, null=True, on_delete=models.CASCADE)
    auzonetrequest = models.ForeignKey(Request, blank=True, null=True, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    owner_voted = models.BooleanField(blank=True, default=False)
    client_voted = models.BooleanField(blank=True, default=False)
    status = models.CharField(max_length=1, choices=STATUS, default='A')

    def __unicode__(self):
        return "Client: " + self.client.username + " Owner: " + self.owner.username + " Type: " + self.order_type + " Created on: " + str(
            self.date_created)


# fist_name, last_name, email, password belongs to superclass User
class PublicUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    communities = models.ManyToManyField(Community)
    birthdate = models.DateField(null=True)
    gender = models.CharField(max_length=1, choices=GENDERS)
    karma = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='uploads/avatars/%Y/%m/%d/')

    def __unicode__(self):
        return self.user.username

    def get_source_filename(self):
        return str(self.avatar.file)

    def save(self, size=(500, 300)):
        """
        Save Photo after ensuring it is not blank.  Resize as needed.
        """

        if not self.id and not self.avatar:
            return

        super(PublicUser, self).save()

        # filename = self.get_source_filename()
        # image = Image.open(filename)

        # image.thumbnail(size, Image.ANTIALIAS)
        # image.save(filename)


class CommunityMessage(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    message_type = models.CharField(ugettext_lazy(u'Message type'), max_length=1, choices=MESSAGE_TYPES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posted_by")
    date_published = models.DateTimeField(auto_now_add=True)
    message_text = models.TextField(ugettext_lazy(u'Texto'))

    def __unicode__(self):
        return self.message_type + " created on " + str(self.date_published)


class CategoriesSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Category
        fields = ('title', 'description')


class CommunitiesSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Community
        fields = (
            'access_type',
            'neighborhood_code',
            'neighborhood_name',
            'street_code',
            'street_name',
            'door_code',
            'coordinatesX',
            'coordinatesY',
            'password',
            'welcome_message'
        )

auzonet/auzonetweb/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy

from .models import Community, Request, Offer, CommunityMessage

GENDERS = (
    ('M', ugettext_lazy(u"Male")),
    ('F', ugettext_lazy(u"Female"))
)

ACCESS_TYPES = (
    ('PU', ugettext_lazy(u"Public")),
    ('PR', ugettext_lazy(u"Private")),
)

SCOPE = (
    ('COM', ugettext_lazy(u"Community")),
    ('CIT', ugettext_lazy(u"City")),
    ('PRO', ugettext_lazy(u"Province")),
    ('COU', ugettext_lazy(u"Country")),
)

STATUS = (
    ('A', ugettext_lazy(u"Active")),
    ('F', ugettext_lazy(u"Finished")),
)


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label=ugettext_lazy(u"Username"), max_length=100)
    password = forms.CharField(required=True, label=ugettext_lazy(u"Password"), max_length=100,
                               widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    class Meta:
        localized_fields = '__all__'

    username = forms.CharField(required=True, label=ugettext_lazy(u"Username"), max_length=100,
                               help_text=ugettext_lazy(u"* Required"))
    first_name = forms.CharField(required=True, label=ugettext_lazy(u"Name"), max_length=100,
                                 help_text=ugettext_lazy(u"* Required"))
    last_name = forms.CharField(required=True, label=ugettext_lazy(u"Surname"), max_length=100,
                                help_text=ugettext_lazy(u"* Required"))
    email = forms.EmailField(required=True, label=ugettext_lazy(u"Email"), max_length=100, widget=forms.EmailInput,
                             help_text=ugettext_lazy(u"* Required"))
    password = forms.CharField(required=True, label=ugettext_lazy(u"Password"), max_length=100,
                               widget=forms.PasswordInput,
                               help_text=ugettext_lazy(u"* Required"))
    birthdate = forms.DateField(required=True, label=ugettext_lazy(u"Birthday"), help_text=ugettext_lazy(u"* Required"))
    gender = forms.ChoiceField(required=True, label=ugettext_lazy(u"Gender"), choices=GENDERS,
                               help_text=ugettext_lazy(u"* Required"))
    avatar = forms.ImageField(required=True, label=ugettext_lazy(u"Avatar"), max_length=100,
                              help_text=ugettext_lazy(u"* Required. Will be your public image in the community."))


class RegisterPublicForm(forms.Form):
    class Meta:
        localized_fields = '__all__'

    birthdate = forms.DateField(required=True, label=ugettext_lazy(u"Birthday"), help_text=ugettext_lazy(u"* Required"))
    gender = forms.ChoiceField(required=True, label=ugettext_lazy(u"Gender"), choices=GENDERS,
                               help_text=ugettext_lazy(u"* Required"))
    avatar = forms.ImageField(required=True, label=ugettext_lazy(u"Avatar"), max_length=100,
                              help_text=ugettext_lazy(u"* Required. Will be your public image in the community."))


class JoinCommunityForm(forms.Form):
    community = forms.ModelChoiceField(queryset=Community.objects.all())


class ProtectedCommunityForm(forms.Form):
    password = forms.CharField(required=True, label=ugettext_lazy(u"Password"), max_length=100,
                               widget=forms.PasswordInput)


class NewCommunityMsgModelForm(ModelForm):
    class Meta:
        model = CommunityMessage
        fields = ['message_type', 'message_text']
        localized_fields = '__all__'


class NewCommunityForm(forms.Form):
    access_type = forms.ChoiceField(label=ugettext_lazy(u"Tipo de acceso"), choices=ACCESS_TYPES)
    neighborhood_code = forms.IntegerField(widget=forms.HiddenInput)
    neighborhood_name = forms.CharField(widget=forms.HiddenInput)
    street_code = forms.IntegerField(widget=forms.HiddenInput)
    street_name = forms.CharField(widget=forms.HiddenInput)
    door_code = forms.IntegerField(widget=forms.HiddenInput)
    coordinatesX = forms.DecimalField(widget=forms.HiddenInput)
    coordinatesY = forms.DecimalField(widget=forms.HiddenInput)
    password = forms.CharField(label=ugettext_lazy(u"Password"), widget=forms.PasswordInput, required=False)
    welcome_message = forms.CharField(label=ugettext_lazy(u"Mensaje de bienvenida"), widget=forms.Textarea, required=False)

    class Meta:
        localized_fields = '__all__'


class NewOfferModelForm(ModelForm):
    class Meta:
        model = Offer
        localized_fields = '__all__'
        fields = ['category', 'title', 'detail', 'price', 'image']


class NewRequestModelForm(ModelForm):
    class Meta:
        model = Request
        localized_fields = '__all__'
        fields = ['category', 'title', 'detail', 'due_date', 'reward', 'image']

auzonet/auzonetweb/templates/auzonetweb/bootcamp.html
{% extends "auzonetweb/base.html" %}
{% load i18n %}
{% block scripts %}
<script>
    $(document).ready(function(){
        $( "#tabs" ).tabs();
    });
</script>
{% endblock %}

{% block title %}::: Auzonet BOOTCAMP :::{% endblock %}
{% block navigation %}
<ul class="nav navbar-nav">
    <li class="active"><a href="#">Home</a></li>
    <li><a href="#about">About</a></li>
    <li><a href="#contact">Contact</a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
        </ul>
    </li>
</ul>

<ul class="nav navbar-nav navbar-right">
    <li><a href="../navbar/">Default</a></li>
    <li><a href="../navbar-static-top/">Static top</a></li>
    <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
</ul>
{% endblock %}
{% block content%}
<h1>Bienvenido al Bootcamp!!</h1>
<div>
    Esta sección de la web pretende ser un campo de pruebas para todas las
    API's que se utilicen.<br/>
    <br/>
    Buena suerte! Y que la fuerza esté contigo!
</div>
<div>
    {% if datasetsjson%}
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">All datasets</a></li>
            <li><a href="#tabs-2">Portales</a></li>
        </ul>
        <div id="tabs-1">
            <p><pre>{{datasetsjson}}</pre></p>
        </div>
    <div id="tabs-2">
            <p><pre>{{portalesjson}}</pre></p>
        </div>
    </div>
    {%endif%}
</div>
{% endblock %}

auzonet/auzonetweb/templates/auzonetweb/confirmation-success.html
{% extends "auzonetweb/base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load static from staticfiles %}
{% block scripts %}
<script>

</script>
{% endblock %}

{% block title %}AuzoNet - {% trans "Acuerdo aceptado" %}{% endblock %}
{% block content%}
<div class="row">
    <div class="col-md-3 col-lg-3"></div>
    <div class="col-md-6 col-lg-6 text-center">
        <h1>{% trans "Fantástico" %}</h1>
        <p>{% trans "Ahora colaboráis juntos, recuerda finalizar tu acuerdo y votar tu experiencia desde la sección 'Acuerdos activos' de tu página de la comunidad cuando consideres que se ha terminado la colaboración." %}</p>
        <p>{% trans "Puedes ponerte en contacto con" %} {{ order.client.first_name }} <a
                href="mailto:{{ order.client.email }}">{{ order.client.email }}</a></p>
        <a class="btn btn-primary" href="{% url "index" %}" role="button">{% trans "Volver al inicio" %}</a>
        <img src="{% static "auzonetweb/images/agreement.png" %}" alt="confirmation-success" class="img img-responsive">
    </div>
    <div class="col-md-3 col-lg-3"></div>
</div> <!-- end my topics-->
{% endblock %}

auzonet/auzonetweb/templates/auzonetweb/register-public-profile.html
{% load static from staticfiles %}
{% load bootstrap3 %}
{% load i18n %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load favtags %}
{% autoescape off %}{% placeFavicon %}{% endautoescape %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bienvenido a Auzonet</title>

    <!-- Bootstrap -->
    <link href="{% static 'auzonetweb/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles -->
    <link href="{% static 'auzonetweb/css/custom_style.css' %}" rel="stylesheet">
    <!-- jQuery UI CSS -->
    <link href="{% static 'jquery-ui/themes/smoothness/jquery-ui.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<div class="container">
    <div class="row">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form RegisterPublicForm %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% trans "Crear" %}
                </button>
            {% endbuttons %}
        </form>
    </div>
</div> <!-- /container -->
<footer>
    <div class="container">
    </div>
</footer>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'jquery/jquery.js' %}"></script>
<script src="{% static 'jquery-ui/jquery-ui.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
{% bootstrap_javascript %}
<script>
    $("#id_birthdate").datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "1900:",
        maxDate: new Date(),
        dateFormat: "yy-mm-dd"
    });
    $("#input-language").on("change keyup", function () {
        $("#form-language").submit();
    });
</script>
</body>
</html>

auzonet/auzonetweb/templates/auzonetweb/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static from staticfiles %}
    {% load bootstrap3 %}
    {% load i18n %}
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    {% load favtags %}
    {% autoescape off %}{% placeFavicon %}{% endautoescape %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% trans "Bienvenido a AuzoNet" %}</title>

    <!-- Custom styles -->
    <link href="{% static 'auzonetweb/css/welcome_style.css' %}" rel="stylesheet">
    <!-- jQuery UI CSS -->
    <link href="{% static 'jquery-ui/themes/smoothness/jquery-ui.css' %}" rel="stylesheet">
    <!-- Google code font -->
    <link href='https://fonts.googleapis.com/css?family=Lato:100,400' rel='stylesheet' type='text/css'>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body background="{% static 'auzonetweb/images/city.jpg' %}">
    <div class="container-fluid">
        <div class="row" id="top-card">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <div class="vertical-center">
                    <h1 id="main-title" class="text-center thin-text">{% trans "Bienvenido a AuzoNet" %}</h1>
                    <h2 id="main-subtitle" class="text-center thin-text">{% trans "La red social de vecinos" %}</h2>
                    <button class="btn btn-primary btn-lg account-buttons center-block btn-block outline" data-toggle="modal" data-target="#loginModal">{% trans "Inicia sesión" %}</button>
                    <button class="btn btn-primary btn-lg account-buttons center-block btn-block outline" data-toggle="modal" data-target="#registerModal">{% trans "Regístrate" %}</button>
                    <a class="btn btn-primary btn-lg account-buttons center-block btn-block outline"
                       href="{% url 'social:begin' "google-oauth2" %}">Sign in with Google</a>
                </div>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div> <!-- /container -->
    <footer>
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form id="form-language" action="{% url 'set_language' %}" method="post" class="pull-right">{% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}" />
                <select name="language" id="input-language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </footer>
    <!-- Modal login-->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="loginModalLabel">{% trans "Iniciar sesión" %}</h4>
                </div>
                <form method="post">
                    <div class="modal-body">
                            {% if errorMessage != None and modal == 'login'%}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <strong>Error:</strong> {{ errorMessage }}
                            </div>
                            {% endif %}
                            {% csrf_token %}
                            {% bootstrap_form loginForm %}
                            <input type="hidden" name="formtype" value="login">
                    </div>
                    <div class="modal-footer">
                        {% buttons %}
                        <button type="submit" class="btn btn-primary center-block">
                            {% trans "Login" %}
                        </button>
                        {% endbuttons %}
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Modal register -->
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="registerModalLabel">{% trans "Register" %}</h4>
                </div>
                <form enctype="multipart/form-data" method="post">
                    <div class="modal-body">
                        {% if errorMessage != None and modal == 'register'%}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <strong>Error:</strong> {{ errorMessage }}
                            </div>
                        {% endif %}
                        {% csrf_token %}
                        {% bootstrap_form registerForm %}
                        <input type="hidden" name="formtype" value="register">
                    </div>
                    <div class="modal-footer">
                        {% buttons %}
                        <button type="submit" class="btn btn-primary center-block">
                            {% trans "Register" %}
                        </button>
                        {% endbuttons %}
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery-ui/jquery-ui.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    {% bootstrap_javascript %}
    <script>
        $("#id_birthdate").datepicker({
          changeMonth: true,
          changeYear: true,
          yearRange: "1900:",
          maxDate: new Date(),
    	  dateFormat: "yy-mm-dd"
        });
        $("#input-language").on("change keyup", function(){
            $("#form-language").submit();
        });
    </script>
    {% if modal == 'register' %}
        <script>
            $(document).ready(function(){
                $("#registerModal").modal('toggle');
            });
        </script>
    {% elif modal == 'login'%}
        <script>
            $(document).ready(function(){
                $("#loginModal").modal('toggle');
            });
        </script>
    {% endif %}
</body>
</html>